# Generated by Django 5.1 on 2024-08-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_delete_usertasks_remove_user_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
